apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s1u8orf6m-java-springboot
  janus-idp.io/tekton: s1u8orf6m-java-springboot
  backstage.io/kubernetes-id: s1u8orf6m-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: s1u8orf6m-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
